package com.dndcharacterhandler.domain.model

enum class SpellCatalogSource { SRD_2014 }

data class SpellCatalogItem(
    val id: String,
    val name: String,
    val level: Int,
    val school: String,
    val description: String,
    val higherLevelDescription: String = "",
    val range: String = "",
    val castingTime: String = "",
    val duration: String = "",
    val components: String = "",
    val material: String = "",
    val materialCost: String = "",
    val isRitual: Boolean = false,
    val requiresConcentration: Boolean = false,
    val attackType: String = "",
    val availableClasses: String = "",
    val damageType: String = "",
    val damageBase: String = "",
    val damageBonusValue: Int = 0,
    val damageBonusIsModifier: Boolean = false,
    val altDamageBase: String = "",
    val altDamageType: String = "",
    val altDamageBonusValue: Int = 0,
    val altDamageBonusIsModifier: Boolean = false,
    val damage: String = "",
    val saveAbility: String = "",
    val saveEffect: String = "",
    val areaOfEffect: String = "",
    val healBase: String = "",
    val healBonusValue: Int = 0,
    val healBonusIsModifier: Boolean = false,
    val healing: String = "",
    val source: SpellCatalogSource = SpellCatalogSource.SRD_2014
) {
    fun toSpell(): Spell =
        Spell(
            catalogId = id,
            name = name,
            level = level,
            school = school,
            isPrepared = level == 0,
            description = description,
            higherLevelDescription = higherLevelDescription,
            range = range,
            castingTime = castingTime,
            duration = duration,
            components = components,
            material = material,
            materialCost = materialCost,
            isRitual = isRitual,
            requiresConcentration = requiresConcentration,
            attackType = attackType,
            availableClasses = availableClasses,
            damageType = damageType,
            damageBase = damageBase,
            damageBonusValue = damageBonusValue,
            damageBonusIsModifier = damageBonusIsModifier,
            altDamageBase = altDamageBase,
            altDamageType = altDamageType,
            altDamageBonusValue = altDamageBonusValue,
            altDamageBonusIsModifier = altDamageBonusIsModifier,
            damage = damage,
            saveAbility = saveAbility,
            saveEffect = saveEffect,
            areaOfEffect = areaOfEffect,
            healBase = healBase,
            healBonusValue = healBonusValue,
            healBonusIsModifier = healBonusIsModifier,
            healing = healing
        )
}
